-- MySQL Script generated by MySQL Workbench
-- 02/10/17 00:02:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brief` VARCHAR(50) NULL,
  `publish_year` INT NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book_has_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_has_employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `book_id`, `employee_id`),
  INDEX `fk_book_has_employee_employee1_idx` (`employee_id` ASC),
  INDEX `fk_book_has_employee_book_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_has_employee_book`
    FOREIGN KEY (`book_id`)
    REFERENCES `library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_employee_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `library`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `library`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'хорошая книга', 1678, 'вапав а.а.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'книга', 2013, 'asfasd d .d.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'qwerty', 2010, 'крылов аа.а.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'book', 1425, 'ыва ыв');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'goodbook', 2010, 'петров петя');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'super book', 1998, 'хороший человек');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'story', 1875, 'плохой человек');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'beautifull book', 1956, 'автор');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'sherlock', 1254, 'author');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'madonna book', 1678, 'child');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'программирование', 2004, 'donald d.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'много и мало', 2006, 'asd s.s.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'мастерок', 2004, 'darom d.d.');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'сделай сам', 2013, 'as das ');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'как сделать все', 1987, 'sdfdfh gf');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'нет ничего проще', 1926, 'отец алексий');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'ifthenelse', 1984, 'брат брата лешё');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'easy to do', 1991, 'король артур');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'mouse and cat', 1848, 'сэр конон');
INSERT INTO `library`.`book` (`id`, `brief`, `publish_year`, `author`) VALUES (DEFAULT, 'big book', 1224, 'мопс');

COMMIT;


-- -----------------------------------------------------
-- Data for table `library`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'денис г', '2012-10-10', 'asdfgfreds@mail.ru');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'ольга с', '2001-10-10', 'vgdrsfsdv@mail.ru');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'маша к', '1995-10-10', 'denis@mail.ru');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'диана д', '2007-04-15', 'qwertypoiu@gmail.com');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'паша ч', '1987-08-13', 'qazxswedc@gmail.com');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'кира у', '1985-07-14', '12345pl@gmail.com');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'павлов а', '1965-03-18', 'dhjyrshgr@gmail.com');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'олег м', '1984-09-23', 'qasdedfgf@gmail.com');
INSERT INTO `library`.`employee` (`id`, `name`, `date_of_birth`, `email`) VALUES (DEFAULT, 'женя я', '1967-01-24', 'sdcfgrtrhyujty@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `library`.`book_has_employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `library`;
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 1, 1);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 2, 2);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 7, 5);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 4, 3);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 9, 1);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 4, 6);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 15, 1);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 17, 2);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 15, 3);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 18, 8);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 19, 7);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 16, 5);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 13, 6);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 15, 9);
INSERT INTO `library`.`book_has_employee` (`id`, `book_id`, `employee_id`) VALUES (DEFAULT, 11, 5);

COMMIT;

